### ISSUE TITLE
Onboarding checklist for @hqtan

### ISSUE THREAD

**Issue by hqtan** [CodeforAustralia/civic-makers-dev-onboarding#1]
Please complete the checklist below to help you get started:

- [x]  Check out our [project git repo](https://github.com/CodeforAustralia/council-emissions-calculator)
- [x]  Get the app running on your `localhost`
- [x]  Join [Code for Australia’s slack channel](https://www.notion.so/Tools-we-use-df677aa289924006ae3356dbdc5a1113).
    - [x]  Introduce yourself on [#civic-makers-climatechange-dev](https://codeforaustralia.slack.com/archives/C01DALXS62K)
    - [x]  join [#civic-makers-climatechange](https://codeforaustralia.slack.com/archives/C01CXCQPF8V) for project updates and meeting links
- [x]  Read the [Civic Makers onboarding docs](https://www.notion.so/b0a26a686de44633a49281cfb7818da2) in Notion if you haven’t already done so
- [x]  Join our [Trello board](https://trello.com/invite/b/ZXaIkclp/6339eeec28570b4e20156fe6f6842b9d/civic-makers-2021-l-use-this-one) and pick a task to work on (Dev tasks have a blue label on it). Make sure to assign yourself to the card!
- [x]  Attend our weekly Wednesday catchups at 6pm to meet the team! (The meeting link will be announced on the day in [#civic-makers-climatechange](https://codeforaustralia.slack.com/archives/C01CXCQPF8V)). Introduce yourself so we can welcome you to the team! :tada:

### Need Help?

- If you’re not sure what to work on, or what to do, or you’re stuck with on of the onboarding tasks, please ask on [#civic-makers-climatechange-dev](https://codeforaustralia.slack.com/archives/C01DALXS62K) . One of the volunteers from the dev team will get back to you as soon as we can (please be patient)
- If you have an idea that you’d like to work on, but isn’t mentioned in our Trello board, please reach out to our Product Lead or the leads team to have a chat. You can find out more about the lead team in [this doc](https://www.notion.so/Meet-the-current-lead-team-47516a1ebb43496fbdee55f258ec1828), and contact them via slack.
    - **N.B:** We love new ideas! But *even more*, we love new ideas that are aligned with the features we want to build, and our current project’s mission/objectives 🙂. See [this doc](https://www.notion.so/Current-project-info-1f6f7e7f36e14a0b8d7d0923de75d14d) to get acquainted with that.

**Comment by hqtan** [comment]
Feel free to add notes here about the tasks you're working on / completed

**Comment by hqtan** [comment]
Remember to get someone's attention in the [#civic-makers-climatechange-dev](https://codeforaustralia.slack.com/archives/C01DALXS62K) slack channel if you get stuck!

**Comment by hqtan** [comment]
But if for some reason you can't get on to the slack channel yet, and you need help with onboarding, please notify the dev leads in a comment like this:
@hqtan (Qing)
@batteries76 (Matt McKenzie)

**Comment by hqtan** [comment]
don't forget to close issue when done!
