### ISSUE TITLE
Onboarding checklist for Lester

### ISSUE THREAD

**Issue by lestercorreya** [CodeforAustralia/civic-makers-dev-onboarding#6]
Please complete the checklist below to help you get started:

- [x]  Check out our [project git repo](https://github.com/CodeforAustralia/council-emissions-calculator)
  - the app we are currently building is deployed [here](https://seechange.codeforaustralia.org/), in case you're wondering  
- [x]  Get the app running on your `localhost`
- [x]  Join [Code for Australia’s (CfA) slack channel](http://slack.codeforaustralia.org/).
    - [x]  Introduce yourself on [#civic-makers-climatechange-dev](https://codeforaustralia.slack.com/archives/C01DALXS62K)
    - [x]  join [#civic-makers-climatechange](https://codeforaustralia.slack.com/archives/C01CXCQPF8V) for project updates and meeting links
- [x]  Read the [Civic Makers onboarding docs](https://www.notion.so/b0a26a686de44633a49281cfb7818da2) in Notion if you haven’t already done so
- [x]  Join our [Trello board](https://trello.com/invite/b/ZXaIkclp/6339eeec28570b4e20156fe6f6842b9d/civic-makers-2021-l-use-this-one).
  - Please read [this doc](https://blue-father-da8.notion.site/How-we-use-Trello-a040d9930e8944948b5eff65065941c5) to learn about how the Trello board is organised.
  - Tip: See the 'How to use this column' Trello card at the top of each column for a quick reminder of what each column means.
- [ ]  Attend our weekly catchups to meet the team! Refer to [this Notion doc](https://www.notion.so/Current-project-info-1f6f7e7f36e14a0b8d7d0923de75d14d) for more details on the date. (The meeting link will be announced on the day in [#civic-makers-climatechange](https://codeforaustralia.slack.com/archives/C01CXCQPF8V)). Introduce yourself so we can welcome you to the team! :tada:
- [ ]  When you're done with all the tasks in this checklist, close this issue, and let us know on [#civic-makers-climatechange-dev](https://codeforaustralia.slack.com/archives/C01DALXS62K) so we can celebrate this important milestone you've reached! 🎉
  - You are now ready to pick a task from the Trello board to work on (Dev tasks have a blue label on it) 🙇. Make sure to assign yourself to the card!

### Need Help?

- If you’re not sure what to work on, or what to do, or you’re stuck with on of the onboarding tasks, please ask on [#civic-makers-climatechange-dev](https://codeforaustralia.slack.com/archives/C01DALXS62K) . One of the volunteers from the dev team will get back to you as soon as we can (please be patient)
- If for some reason you're having issues getting on to the slack channel, please notify the dev leads in a comment in this onboarding github issue that you've created. Notify the dev leads using their github handles **@batteries76** (Matt McKenzie) and **@hqtan** (Qing). See [this comment in this onboarding issue](https://github.com/CodeforAustralia/civic-makers-dev-onboarding/issues/1#issuecomment-1035553988) for example.
- If you have an idea that you’d like to work on, but isn’t mentioned in our Trello board, please reach out to our Product Lead or the leads team to have a chat. You can find out more about the lead team in [this doc](https://www.notion.so/Meet-the-current-lead-team-47516a1ebb43496fbdee55f258ec1828), and contact them via slack.
    - **N.B:** We love new ideas! But *even more*, we love new ideas that are aligned with the features we want to build, and our current project’s mission/objectives 🙂. See [this doc](https://www.notion.so/Current-project-info-1f6f7e7f36e14a0b8d7d0923de75d14d) to get acquainted with that.
